<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CefSharp.Common.NETCore" Version="97.1.61" />
    <PackageReference Include="CefSharp.Wpf.NETCore" Version="97.1.61" />
    <PackageReference Include="InteractiveDataDisplay.NetCore.WPF" Version="1.0.2" />
    <PackageReference Include="System.Drawing.Common" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="chart.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="echarts.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\echarts.common.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\echarts.common.js.map">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\echarts.common.min.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\echarts.esm.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\echarts.esm.js.map">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\echarts.esm.min.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\echarts.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\echarts.js.map">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\echarts.min.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\echarts.simple.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\echarts.simple.js.map">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\echarts.simple.min.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\extension\bmap.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\extension\bmap.js.map">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\extension\bmap.min.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\extension\dataTool.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\extension\dataTool.js.map">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\extension\dataTool.min.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\jquery\idangerous.swiper2.7.6.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\jquery\idangerous.swiper2.7.6.min.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\jquery\jquery-1.11.3.min.js">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\style\index.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="EChart\index.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Page Update="MainWindowBitMapV1.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="MainWindowBitMapV0.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="MainWindowChart.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="MainWindowDC.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="MainWindowCef.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

</Project>
