<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="TestUser.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ViewModel\" />
    <Folder Include="Task\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SqlSugarCore" Version="5.0.2.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MKSS.IRepository\MKSS.IRepository.csproj" />
  </ItemGroup>

</Project>
