<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>bitbug_favicon.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="UILaoHua\Util\DataAging.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
    <None Remove="MainWindow.xaml~RFc95dc.TMP" />
    <None Remove="Resources\Images\biaoding.png" />
    <None Remove="Resources\Images\huanjing.png" />
    <None Remove="Resources\Images\logo.png" />
    <None Remove="Resources\Images\logo2.png" />
    <None Remove="Resources\Images\logo3.png" />
    <None Remove="Resources\Images\logo5.png" />
    <None Remove="Resources\Images\shebei.png" />
    <None Remove="Resources\Images\shezhi.png" />
    <None Remove="Resources\Images\tongji.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="5.5.5" />
    <PackageReference Include="GodSharp.SerialPort" Version="1.2.0.6" />
    <PackageReference Include="LiveCharts.Wpf.NetCore3" Version="0.9.7" />
    <PackageReference Include="MaterialDesignColors" Version="2.0.0" />
    <PackageReference Include="MaterialDesignThemes" Version="4.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.NewtonsoftJson" Version="5.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="5.0.1" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="5.0.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.31" />
    <PackageReference Include="Prism.Core" Version="8.0.0.1909" />
    <PackageReference Include="Prism.Wpf" Version="8.0.0.1909" />
    <PackageReference Include="PropertyChanged.Fody" Version="3.3.2" />
    <PackageReference Include="RestSharp" Version="106.12.0" />
    <PackageReference Include="SharpVectors" Version="1.7.1" />
    <PackageReference Include="Stylet.Start" Version="1.3.5" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\BiaoDing\ViewModels\" />
    <Folder Include="Areas\BiaoDing\Views\" />
    <Folder Include="Areas\LaoHua\ViewModels\" />
    <Folder Include="Areas\LaoHua\Views\" />
    <Folder Include="Areas\ShengChan\" />
    <Folder Include="Areas\ShengChan\Views\" />
    <Folder Include="Areas\ShengChan\ViewModels\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MKSS.APP.LaoHuaService\MKSS.APP.LaoHuaService.csproj" />
    <ProjectReference Include="..\MKSS.Common\MKSS.Common.csproj" />
    <ProjectReference Include="..\MKSS.CustomControl\CircleProcessBar\CircleProcessBar.csproj" />
    <ProjectReference Include="..\MKSS.CustomControl\TemperatureGuageControl\TemperatureGuageControl.csproj" />
    <ProjectReference Include="..\MKSS.ICommon\MKSS.ICommon.csproj" />
    <ProjectReference Include="..\MKSS.IRepository\MKSS.IRepository.csproj" />
    <ProjectReference Include="..\MKSS.NModbus\MKSS.NModbus.csproj" />
    <ProjectReference Include="..\MKSS.Repository\MKSS.Repository.csproj" />
    <ProjectReference Include="..\MKSS.Service.LaoHua\MKSS.Service.LaoHua.csproj" />
    <ProjectReference Include="..\MKSS.Util\MKSS.Util.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ScottPlot">
      <HintPath>lib\ScottPlot.dll</HintPath>
    </Reference>
    <Reference Include="ScottPlot.Cookbook">
      <HintPath>lib\ScottPlot.Cookbook.dll</HintPath>
    </Reference>
    <Reference Include="ScottPlot.WPF">
      <HintPath>lib\ScottPlot.WPF.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\biaoding.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\huanjing.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\logo2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\logo3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\logo5.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\shebei.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\shezhi.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\tongji.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.resx</DependentUpon>
    </Compile>
    <Compile Update="UILaoHua\UIScrwSelect.xaml.cs">
      <DependentUpon>UIScrwSelect.xaml</DependentUpon>
    </Compile>
    <Compile Update="UILaoHua\UISerialNo.xaml.cs">
      <DependentUpon>UISerialNo.xaml</DependentUpon>
    </Compile>
    <Compile Update="UserCommon\WaitWindow.xaml.cs">
      <DependentUpon>WaitWindow.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Page Update="UILaoHua\UIScrwSelect.xaml">
      <SubType>Designer</SubType>
    </Page>
    <Page Update="UILaoHua\UISerialNo.xaml">
      <SubType>Designer</SubType>
    </Page>
    <Page Update="UserCommon\WaitWindow.xaml">
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties appsettings_1json__JsonSchema="" /></VisualStudio></ProjectExtensions>

</Project>
