<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="InteractiveDataDisplay.NetCore.WPF" Version="1.0.2" />
    <PackageReference Include="System.Reactive" Version="5.0.0" />
  </ItemGroup>
</Project>